/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import * as nestAccessControl from "nest-access-control";
import * as defaultAuthGuard from "../../auth/defaultAuth.guard";
import { AttributeService } from "../attribute.service";
import { AclValidateRequestInterceptor } from "../../interceptors/aclValidateRequest.interceptor";
import { AclFilterResponseInterceptor } from "../../interceptors/aclFilterResponse.interceptor";
import { AttributeCreateInput } from "./AttributeCreateInput";
import { Attribute } from "./Attribute";
import { AttributeFindManyArgs } from "./AttributeFindManyArgs";
import { AttributeWhereUniqueInput } from "./AttributeWhereUniqueInput";
import { AttributeUpdateInput } from "./AttributeUpdateInput";
import { AttributeGroupFindManyArgs } from "../../attributeGroup/base/AttributeGroupFindManyArgs";
import { AttributeGroup } from "../../attributeGroup/base/AttributeGroup";
import { AttributeGroupWhereUniqueInput } from "../../attributeGroup/base/AttributeGroupWhereUniqueInput";
import { ItemAttributeFindManyArgs } from "../../itemAttribute/base/ItemAttributeFindManyArgs";
import { Item } from "../../item/base/Item";
import { ItemAttribute } from "../../itemAttribute/base/ItemAttribute";
import { ItemAttributeWhereUniqueInput } from "../../itemAttribute/base/ItemAttributeWhereUniqueInput";

@swagger.ApiBearerAuth()
@common.UseGuards(defaultAuthGuard.DefaultAuthGuard, nestAccessControl.ACGuard)
export class AttributeControllerBase {
  constructor(
    protected readonly service: AttributeService,
    protected readonly rolesBuilder: nestAccessControl.RolesBuilder
  ) {}
  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Attribute })
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "create",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async createAttribute(
    @common.Body() data: AttributeCreateInput
  ): Promise<Attribute> {
    return await this.service.createAttribute({
      data: data,
      select: {
        createdAt: true,
        id: true,
        key: true,
        label: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get()
  @swagger.ApiOkResponse({ type: [Attribute] })
  @ApiNestedQuery(AttributeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "read",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attributes(@common.Req() request: Request): Promise<Attribute[]> {
    const args = plainToClass(AttributeFindManyArgs, request.query);
    return this.service.attributes({
      ...args,
      select: {
        createdAt: true,
        id: true,
        key: true,
        label: true,
        typeField: true,
        updatedAt: true,
      },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Attribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "read",
    possession: "own",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async attribute(
    @common.Param() params: AttributeWhereUniqueInput
  ): Promise<Attribute | null> {
    const result = await this.service.attribute({
      where: params,
      select: {
        createdAt: true,
        id: true,
        key: true,
        label: true,
        typeField: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.UseInterceptors(AclValidateRequestInterceptor)
  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Attribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async updateAttribute(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() data: AttributeUpdateInput
  ): Promise<Attribute | null> {
    try {
      return await this.service.updateAttribute({
        where: params,
        data: data,
        select: {
          createdAt: true,
          id: true,
          key: true,
          label: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Attribute })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "delete",
    possession: "any",
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async deleteAttribute(
    @common.Param() params: AttributeWhereUniqueInput
  ): Promise<Attribute | null> {
    try {
      return await this.service.deleteAttribute({
        where: params,
        select: {
          createdAt: true,
          id: true,
          key: true,
          label: true,
          typeField: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/AttributeGroups")
  @ApiNestedQuery(AttributeGroupFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "AttributeGroup",
    action: "read",
    possession: "any",
  })
  async findAttributeGroups(
    @common.Req() request: Request,
    @common.Param() params: AttributeWhereUniqueInput
  ): Promise<AttributeGroup[]> {
    const query = plainToClass(AttributeGroupFindManyArgs, request.query);
    const results = await this.service.findAttributeGroups(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        label: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/AttributeGroups")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async connectAttributeGroups(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: AttributeGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      AttributeGroups: {
        connect: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/AttributeGroups")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async updateAttributeGroups(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: AttributeGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      AttributeGroups: {
        set: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/AttributeGroups")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async disconnectAttributeGroups(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: AttributeGroupWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      AttributeGroups: {
        disconnect: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.UseInterceptors(AclFilterResponseInterceptor)
  @common.Get("/:id/ItemAttributes")
  @ApiNestedQuery(ItemAttributeFindManyArgs)
  @nestAccessControl.UseRoles({
    resource: "ItemAttribute",
    action: "read",
    possession: "any",
  })
  async findItemAttributes(
    @common.Req() request: Request,
    @common.Param() params: AttributeWhereUniqueInput
  ): Promise<ItemAttribute[]> {
    const query = plainToClass(ItemAttributeFindManyArgs, request.query);
    const results = await this.service.findItemAttributes(params.id, {
      ...query,
      select: {
        Item: {
          select: {
            id: true,
          },
        },

        attribute: {
          select: {
            id: true,
          },
        },

        createdAt: true,
        id: true,
        updatedAt: true,
        value: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/ItemAttributes")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async connectItemAttributes(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: ItemAttributeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ItemAttributes: {
        connect: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/ItemAttributes")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async updateItemAttributes(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: ItemAttributeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ItemAttributes: {
        set: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/ItemAttributes")
  @nestAccessControl.UseRoles({
    resource: "Attribute",
    action: "update",
    possession: "any",
  })
  async disconnectItemAttributes(
    @common.Param() params: AttributeWhereUniqueInput,
    @common.Body() body: ItemAttributeWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      ItemAttributes: {
        disconnect: body,
      },
    };
    await this.service.updateAttribute({
      where: params,
      data,
      select: { id: true },
    });
  }
}
