/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { AttributeGroupListRelationFilter } from "../../attributeGroup/base/AttributeGroupListRelationFilter";
import { ValidateNested, IsOptional, IsEnum } from "class-validator";
import { Type } from "class-transformer";
import { ItemAttributeListRelationFilter } from "../../itemAttribute/base/ItemAttributeListRelationFilter";
import { StringFilter } from "../../util/StringFilter";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { EnumAttributeTypeField } from "./EnumAttributeTypeField";

@InputType()
class AttributeWhereInput {
  @ApiProperty({
    required: false,
    type: () => AttributeGroupListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AttributeGroupListRelationFilter)
  @IsOptional()
  @Field(() => AttributeGroupListRelationFilter, {
    nullable: true,
  })
  AttributeGroups?: AttributeGroupListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => ItemAttributeListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ItemAttributeListRelationFilter)
  @IsOptional()
  @Field(() => ItemAttributeListRelationFilter, {
    nullable: true,
  })
  ItemAttributes?: ItemAttributeListRelationFilter;

  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  key?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  label?: StringNullableFilter;

  @ApiProperty({
    required: false,
    enum: EnumAttributeTypeField,
  })
  @IsEnum(EnumAttributeTypeField)
  @IsOptional()
  @Field(() => EnumAttributeTypeField, {
    nullable: true,
  })
  typeField?: "Text" | "Dropdown";
}

export { AttributeWhereInput as AttributeWhereInput };
